/*
 *  This file will create a config file using YAML.
 *  Created On 19 September 2020
 */

import Conf from 'conf'
import yaml from 'js-yaml'
import { DateTime } from 'luxon'
import path from 'path'

import defaults from './defaults.js'

const config = new Conf({
    projectSuffix: '',
    cwd: path.join(process.cwd(), 'data'),
    configName: 'config',
    fileExtension: 'yml',
    serialize: data => {
        return `# Run control for mantu.\n# Last modified on ${DateTime.local().toFormat(
            'ccc, dd LLLL yyyy',
        )} at ${DateTime.local().toFormat(
            'hh:mm:ss a',
        )}\n# This file is automatically generated and should not be edited.\n# Unless you know what you are doing!\n\n`.concat(
            yaml.safeDump(data, {
                indent: 4,
            }),
        )
    },
    deserialize: yaml.safeLoad,
})

export default defaults(config)
