/*
 *  This file will create a config file using YAML.
 *  Created On 19 September 2020
 */

import utilities from '@vasanthdeveloper/utilities'
import chalk from 'chalk'
import Conf from 'conf'
import yaml from 'js-yaml'
import { DateTime } from 'luxon'
import path from 'path'

import logger from '../logger/app.js'
import defaults from './defaults.js'
import schema from './schema.js'

export let config

// const config =

export default async () => {
    config = new Conf({
        defaults,
        projectSuffix: '',
        cwd: path.join(process.cwd(), 'data'),
        configName: 'config',
        fileExtension: 'yml',
        serialize: data => {
            return `# Run control for mantu.\n# Last modified on ${DateTime.local().toFormat(
                'ccc, dd LLLL yyyy',
            )} at ${DateTime.local().toFormat(
                'hh:mm:ss a',
            )}\n# This file is automatically generated and should not be edited.\n# Unless you know what you are doing!\n\n`.concat(
                yaml.safeDump(data, {
                    indent: 4,
                }),
            )
        },
        deserialize: yaml.safeLoad,
    })

    // validate the config file
    const validate = await utilities.promise.handle(
        schema.validateAsync(config.store),
    )

    // handle validation errors
    if (validate.error)
        logger.error(
            `Invalid config file due to 👇\n${validate.error.message}`,
            2,
        )

    logger.info('Finished reading run control')
    logger.verbose(
        `Run control read from 👇\n${chalk.gray.dim.underline(config.path)}`,
    )
}
